-- Use sqlcmd variables for UAMI_NAME and UAMI_PRINCIPAL_ID
DROP USER IF EXISTS [$(UAMI_NAME)]
go
CREATE USER [$(UAMI_NAME)] FROM EXTERNAL PROVIDER WITH OBJECT_ID='$(UAMI_PRINCIPAL_ID)';
ALTER ROLE db_datareader ADD MEMBER [$(UAMI_NAME)];
ALTER ROLE db_datawriter ADD MEMBER [$(UAMI_NAME)];
ALTER ROLE db_ddladmin ADD MEMBER [$(UAMI_NAME)];
go
